#!/bin/bash
scriptdir=`dirname $0`
rootdir=`readlink -f ${scriptdir}`

##############################
# Script buils information #
##############################
versionFile="${rootdir}/version.txt"
if [[ ! -f "${versionFile}" ]]; then
    echo "Missing build file: ${versionFile}"
    exit 1
fi

build=$(grep -E '^Version:' "${versionFile}" | awk '{print $2}')

##############################
# Some convenience functions #
##############################
prematureExit () {
    echo "${1}"
    exit -1
}

head -4 ${versionFile}
export PYTHONPATH=${rootdir}/deps
runningFromAPIC=1
acidiagCmd="acidiag"
acidiagToInvoke=$(type -P ${acidiagCmd})
if [[ ! -x ${acidiagToInvoke} ]]; then
    runningFromAPIC=0
    echo "Executing not from the controller"
else
    echo "Executing from APIC"
fi

if [[ $# -eq 0 ]]; then
    set -- --help
fi

if [[ ${runningFromAPIC} -eq 0 ]]; then
    pythonVersion="3.12"
    pythonCmd="python${pythonVersion}"
    defaultPythonFallBack="/vol/apicbin/gmeo/utils/bin/${pythonCmd}"

    # 1. Try python3.12 from PATH
    pythonToInvoke=$(type -P "${pythonCmd}" 2>/dev/null)
    # 2. Fallback to default path
    if [[ ! -x "${pythonToInvoke}" ]]; then
        if [[ -x "${defaultPythonFallBack}" ]]; then
            pythonToInvoke="${defaultPythonFallBack}"
        fi
    fi
    # 3. Try python3 if version >= 3.12
    if [[ ! -x "${pythonToInvoke}" ]]; then
        python3Path=$(type -P python3 2>/dev/null)
        if [[ -x "${python3Path}" ]]; then
            pyVersion=$("${python3Path}" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
            pyMajor=$(echo "${pyVersion}" | cut -d. -f1)
            pyMinor=$(echo "${pyVersion}" | cut -d. -f2)

            if [[ "${pyMajor}" -eq 3 && "${pyMinor}" -ge 12 ]]; then
                pythonToInvoke="${python3Path}"
            fi
        fi
    fi

    if [[ ! -x "${pythonToInvoke}" ]]; then
        prematureExit "Cannot find python3.12 or a compatible python3 (>=3.12) anywhere, and i need it"
    fi
    ${pythonToInvoke} ${rootdir}/ESGMigrationAssistant.py "$@"
    exit $?
fi

cd ${rootdir}
/opt/cisco/system-venv3/bin/python3 ${rootdir}/ESGMigrationAssistant.py --fromApic "$@"
exit $?
